name: Backup
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main

env:
  repos: "aonez/Keka"

jobs:
  build:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Backup
        run: |
          rm -rf *
          latest_version=$(curl -4sL https://data.jsdelivr.com/v1/package/gh/$repos | jq -r .versions[0])
          echo $latest_version
          wget -q https://github.com/$repos/releases/download/v$latest_version/Keka-$latest_version.dmg &> /dev/null            
          7z -v20m a -t7z v2rayN-$(date +"%Y-%m-%d").7z *.dmg
          rm -f *.dmg
          echo -e "|    Size   |     jsDelivr  | FastGit |\n|  ---  |  ---  |  ---  |" > README.md
          shopt -s extglob
          for file in $(ls !(*.md)); do
          echo "| $(expr $(wc -c < $file )  / 1000000  | numfmt --to=iec-i --suffix=MB --format="%f") | [$file](https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/$file) | [$file](https://raw.fastgit.org/${{ github.repository }}/main/$file) |" >> README.md
          done
          mkdir -p .github/workflows
          wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null
          git config --global init.defaultBranch main
          git init
          git add .
          git config user.name "googleians"
          git config user.email "77716481+googleians@users.noreply.github.com"
          git commit -m "Version ${latest_version}"
          git tag -a "$(date +"%Y-%m-%d")" -m "$(date +"%Y-%m-%d")"
          git remote add release "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -u --follow-tags release main -f
